version: '3'

services:
    db:
        image: postgres:11
        ports:
            - '5433:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: salomon
    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
volumes:
  postgres_data: