# Generated by Django 3.0.7 on 2020-10-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200927_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='current_possibility',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previous_possibility',
            field=models.FloatField(),
        ),
    ]
