# Generated by Django 3.0.7 on 2020-10-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201004_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
