name: Testing
on: push

jobs:
  projectTesting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django UnitTest
      run: |
        pip3 install --user django
        python3 manage.py test
